# Generated by Django 2.1.7 on 2020-10-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('url', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('content_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
